In [1]:
import numpy as np
from sklearn.calibrationdatasets import load_iris

/Users/serdarbozoglan/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/Users/serdarbozoglan/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/serdarbozoglan/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/serdarbozoglan/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [2]:
iris =load_iris()

In [3]:
type(iris)

sklearn.utils.Bunch

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y = iris.target

In [8]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
## One hot encoding
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

from keras.utils import to_categorical

In [12]:
y.shape

(150,)

In [13]:
y = to_categorical(y)

In [14]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=42)

In [17]:
X_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler_object = MinMaxScaler()

In [21]:
# Scale for ONLY TRAINING DATA
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [23]:
scaled_X_train = scaler_object.transform(X_train)

In [24]:
scaled_X_test = scaler_object.transform(X_test)

In [25]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [28]:
from keras.models import Sequential
from keras.layers import Dense 

In [31]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu')) # layers I put here is 2xfeatures, no right answer
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax')) # output layer will have 3 classes
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [32]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(scaled_X_train, y_train, epochs=500, verbose=2)

Epoch 1/500
 - 0s - loss: 0.5084 - acc: 0.6900
Epoch 2/500
 - 0s - loss: 0.5064 - acc: 0.6900
Epoch 3/500
 - 0s - loss: 0.5043 - acc: 0.6900
Epoch 4/500
 - 0s - loss: 0.5023 - acc: 0.6900
Epoch 5/500
 - 0s - loss: 0.4999 - acc: 0.6900
Epoch 6/500
 - 0s - loss: 0.4979 - acc: 0.6900
Epoch 7/500
 - 0s - loss: 0.4958 - acc: 0.7100
Epoch 8/500
 - 0s - loss: 0.4937 - acc: 0.7100
Epoch 9/500
 - 0s - loss: 0.4918 - acc: 0.7100
Epoch 10/500
 - 0s - loss: 0.4900 - acc: 0.7100
Epoch 11/500
 - 0s - loss: 0.4881 - acc: 0.7000
Epoch 12/500
 - 0s - loss: 0.4869 - acc: 0.6900
Epoch 13/500
 - 0s - loss: 0.4849 - acc: 0.6900
Epoch 14/500
 - 0s - loss: 0.4829 - acc: 0.7100
Epoch 15/500
 - 0s - loss: 0.4813 - acc: 0.7200
Epoch 16/500
 - 0s - loss: 0.4791 - acc: 0.7200
Epoch 17/500
 - 0s - loss: 0.4772 - acc: 0.7300
Epoch 18/500
 - 0s - loss: 0.4761 - acc: 0.7500
Epoch 19/500
 - 0s - loss: 0.4734 - acc: 0.7900
Epoch 20/500
 - 0s - loss: 0.4715 - acc: 0.8200
Epoch 21/500
 - 0s - loss: 0.4697 - acc: 0.8200
E

Epoch 171/500
 - 0s - loss: 0.1971 - acc: 0.9200
Epoch 172/500
 - 0s - loss: 0.1964 - acc: 0.9200
Epoch 173/500
 - 0s - loss: 0.1954 - acc: 0.9200
Epoch 174/500
 - 0s - loss: 0.1944 - acc: 0.9200
Epoch 175/500
 - 0s - loss: 0.1933 - acc: 0.9300
Epoch 176/500
 - 0s - loss: 0.1922 - acc: 0.9200
Epoch 177/500
 - 0s - loss: 0.1915 - acc: 0.9300
Epoch 178/500
 - 0s - loss: 0.1910 - acc: 0.9400
Epoch 179/500
 - 0s - loss: 0.1905 - acc: 0.9400
Epoch 180/500
 - 0s - loss: 0.1895 - acc: 0.9400
Epoch 181/500
 - 0s - loss: 0.1880 - acc: 0.9400
Epoch 182/500
 - 0s - loss: 0.1869 - acc: 0.9300
Epoch 183/500
 - 0s - loss: 0.1855 - acc: 0.9300
Epoch 184/500
 - 0s - loss: 0.1848 - acc: 0.9300
Epoch 185/500
 - 0s - loss: 0.1836 - acc: 0.9300
Epoch 186/500
 - 0s - loss: 0.1843 - acc: 0.9400
Epoch 187/500
 - 0s - loss: 0.1856 - acc: 0.9300
Epoch 188/500
 - 0s - loss: 0.1856 - acc: 0.9300
Epoch 189/500
 - 0s - loss: 0.1815 - acc: 0.9300
Epoch 190/500
 - 0s - loss: 0.1805 - acc: 0.9300
Epoch 191/500
 - 0s 

 - 0s - loss: 0.1114 - acc: 0.9600
Epoch 339/500
 - 0s - loss: 0.1132 - acc: 0.9600
Epoch 340/500
 - 0s - loss: 0.1153 - acc: 0.9600
Epoch 341/500
 - 0s - loss: 0.1154 - acc: 0.9600
Epoch 342/500
 - 0s - loss: 0.1135 - acc: 0.9600
Epoch 343/500
 - 0s - loss: 0.1113 - acc: 0.9700
Epoch 344/500
 - 0s - loss: 0.1106 - acc: 0.9600
Epoch 345/500
 - 0s - loss: 0.1094 - acc: 0.9600
Epoch 346/500
 - 0s - loss: 0.1088 - acc: 0.9500
Epoch 347/500
 - 0s - loss: 0.1101 - acc: 0.9400
Epoch 348/500
 - 0s - loss: 0.1108 - acc: 0.9300
Epoch 349/500
 - 0s - loss: 0.1133 - acc: 0.9400
Epoch 350/500
 - 0s - loss: 0.1125 - acc: 0.9500
Epoch 351/500
 - 0s - loss: 0.1099 - acc: 0.9300
Epoch 352/500
 - 0s - loss: 0.1071 - acc: 0.9500
Epoch 353/500
 - 0s - loss: 0.1074 - acc: 0.9500
Epoch 354/500
 - 0s - loss: 0.1075 - acc: 0.9600
Epoch 355/500
 - 0s - loss: 0.1078 - acc: 0.9700
Epoch 356/500
 - 0s - loss: 0.1091 - acc: 0.9700
Epoch 357/500
 - 0s - loss: 0.1079 - acc: 0.9600
Epoch 358/500
 - 0s - loss: 0.1072

In [35]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [36]:
# If you have a unscaled new data you MUST SCALE IT FIRST

In [37]:
model.predict(scaled_X_test) # produces probabilities

array([[2.13164021e-04, 9.81757462e-01, 1.80293806e-02],
       [9.97433126e-01, 2.56691920e-03, 1.13749132e-11],
       [5.46677829e-13, 7.13184418e-04, 9.99286830e-01],
       [7.33969864e-05, 9.08973753e-01, 9.09529105e-02],
       [9.80325513e-06, 7.89654672e-01, 2.10335553e-01],
       [9.93724406e-01, 6.27559144e-03, 2.18654234e-10],
       [4.10486665e-03, 9.93300676e-01, 2.59450777e-03],
       [2.30606853e-10, 4.47720243e-03, 9.95522857e-01],
       [5.87900956e-07, 1.43789858e-01, 8.56209576e-01],
       [1.37770339e-03, 9.92205322e-01, 6.41697505e-03],
       [1.25231509e-07, 1.21375203e-01, 8.78624618e-01],
       [9.96497333e-01, 3.50273447e-03, 9.61306798e-11],
       [9.97912228e-01, 2.08769995e-03, 1.34042985e-11],
       [9.96917129e-01, 3.08285072e-03, 6.14986187e-11],
       [9.98822868e-01, 1.17707253e-03, 3.92200291e-12],
       [6.55721524e-05, 9.52137768e-01, 4.77965660e-02],
       [1.24312713e-10, 3.17361951e-03, 9.96826410e-01],
       [1.85296137e-03, 9.91685

In [39]:
model.predict_classes(scaled_X_test) # you will have predicted classes in orijinal form not as one-hot encoded

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [40]:
predictions = model.predict_classes(scaled_X_test)

In [41]:
y_test.argmax(axis=1) # we have the original classes back. from one-hot encoded to original class

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [42]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [44]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]])

In [45]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

   micro avg       0.96      0.96      0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [46]:
accuracy_score(y_test.argmax(axis=1), predictions)

0.96

In [47]:
#model.save('myfirstmodel.h5') # if you rerun it will overwrite to avoid this after run comment out this line

In [48]:
from keras.models import load_model

In [49]:
new_model = load_model('myfirstmodel.h5')

In [50]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])