In [1]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
        
        return str_text 

In [2]:
read_file('moby_dick_four_chapters.txt')

'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

In [4]:
import spacy
nlp =spacy.load('en', disable=['parser', 'tagger', 'ner']) # to faster tokenization we dsiable other features

In [5]:
nlp.max_length = 1198623 

In [6]:
def seperate_punc (doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n']

In [7]:
d = read_file('moby_dick_four_chapters.txt')

In [8]:
tokens = seperate_punc(d)

In [9]:
tokens

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such',
 'an',
 'upper',
 'hand',
 '

In [10]:
len(tokens)

11394

In [12]:
## we will feed 25 words and will predict 26th word (target word)
## 25 words --> network 26. word
## 25 word might be enough to predict the next word, less word may not be enough


train_len = 25 + 1
text_sequences = []

for i in range(train_len, len(tokens)):
    sequence = tokens[i-train_len:i]
    
    text_sequences.append(sequence)

In [13]:
type(text_sequences)

list

In [14]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [15]:
text_sequences[1] # one word token over (one word forward sliding)

['me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore']

In [18]:
' '.join(text_sequences[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [19]:
' '.join(text_sequences[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [20]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

/Users/serdarbozoglan/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [21]:
tokenizer.fit_on_texts(text_sequences)

In [22]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [37]:
tokenizer.index_word
# each word has a unique ID

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'you',
 18: 'this',
 19: 'at',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'on',
 25: 'be',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'no',
 38: 'about',
 39: 'into',
 40: 'by',
 41: 'were',
 42: 'out',
 43: 'or',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'have',
 48: 'an',
 49: 'upon',
 50: 'little',
 51: 'some',
 52: 'old',
 53: 'like',
 54: 'if',
 55: 'they',
 56: 'would',
 57: 'do',
 58: 'over',
 59: 'landlord',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: 'here',
 65: 'head',
 66: "n't",
 67: 'night',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'though',
 74: 'time',
 75: 'other',
 76: 'very',
 77: 'go',
 78: 'these',
 79: 'more',
 80: 'first',
 81: 'sort',


In [38]:
sequences[0]
# index of words in sequences[0] list

[964,
 14,
 265,
 51,
 263,
 416,
 87,
 222,
 129,
 111,
 962,
 262,
 50,
 43,
 37,
 321,
 7,
 23,
 555,
 3,
 150,
 261,
 6,
 2704,
 14,
 24]

In [36]:
for i in sequences[0]:
    print(f"{i :{5}} {tokenizer.index_word[i]:_>{10}}")

  964 ______call
   14 ________me
  265 ___ishmael
   51 ______some
  263 _____years
  416 _______ago
   87 _____never
  222 ______mind
  129 _______how
  111 ______long
  962 _precisely
  262 ____having
   50 ____little
   43 ________or
   37 ________no
  321 _____money
    7 ________in
   23 ________my
  555 _____purse
    3 _______and
  150 ___nothing
  261 particular
    6 ________to
 2704 __interest
   14 ________me
   24 ________on


In [40]:
tokenizer.word_counts
# Shows each word appears how many times in the corpus

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1029),
             ('money', 120),
             ('in', 5647),
             ('my', 1812),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7176),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 442),
             ('the', 15566),
             ('watery', 26),
  

In [41]:
vocabulary_size = len(tokenizer.word_counts)

In [43]:
vocabulary_size
# unique words number in chapter 4

2709

In [45]:
type(sequences)

list

In [46]:
import numpy as np

In [47]:
sequences = np.array(sequences)

In [49]:
sequences
# each row represents a single line in a text (each row shift one word over)
# last column (26th word/target word) is our label column (y column) rest are features (X columns)

array([[ 964,   14,  265, ..., 2704,   14,   24],
       [  14,  265,   51, ...,   14,   24,  965],
       [ 265,   51,  263, ...,   24,  965,    5],
       ...,
       [ 960,   12,  168, ...,  264,   53,    2],
       [  12,  168, 2703, ...,   53,    2, 2709],
       [ 168, 2703,    3, ...,    2, 2709,   26]])

In [50]:
from keras.utils import to_categorical

In [54]:
X = sequences[:, :-1] # Grab every column but last one
X

array([[ 964,   14,  265, ...,    6, 2704,   14],
       [  14,  265,   51, ..., 2704,   14,   24],
       [ 265,   51,  263, ...,   14,   24,  965],
       ...,
       [ 960,   12,  168, ...,   11,  264,   53],
       [  12,  168, 2703, ...,  264,   53,    2],
       [ 168, 2703,    3, ...,   53,    2, 2709]])

In [55]:
y = sequences[:,-1] # grabs the very last column
y

array([  24,  965,    5, ...,    2, 2709,   26])

In [56]:
y = to_categorical(y, num_classes=vocabulary_size+1) # class number is vocab size+1 it needs hold 0 as well

In [57]:
seq_len = X.shape[1] 
# seq_len grabs the number of 25 (which we set earlier)

In [58]:
X.shape

(11368, 25)

In [59]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding

In [65]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, seq_len, input_length=seq_len)) # input dimension, output dimension, input_length
    model.add(LSTM(seq_len*2, return_sequences=True)) # times of seq_len (2 times or 3 times etc, for this case 25X)
    model.add(LSTM(seq_len*2))
    model.add(Dense(50, activation='relu'))
    
    model.add(Dense(vocabulary_size, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    
    return model

In [67]:
model = create_model(vocabulary_size+1, seq_len)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 25, 25)            67750     
_________________________________________________________________
lstm_5 (LSTM)                (None, 25, 50)            15200     
_________________________________________________________________
lstm_6 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_5 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_6 (Dense)              (None, 2710)              138210    
Total params: 243,910
Trainable params: 243,910
Non-trainable params: 0
_________________________________________________________________


In [68]:
from pickle import dump, load

In [70]:
model.fit(X, y, batch_size=128, epochs=2, verbose=1)

Epoch 1/2
11368/11368 [==============================] - 6s 516us/step - loss: 7.0358 - acc: 0.0292
Epoch 2/2
11368/11368 [==============================] - 4s 374us/step - loss: 6.3800 - acc: 0.0527


In [71]:
model.save('my_mobydick_model.h5')

In [72]:
dump(tokenizer, open('my_simpletokenizer', 'wb'))

In [88]:
from keras.preprocessing.sequence import pad_sequences

In [103]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    
    output_text = []
    input_text = seed_text
    
    for i in range(num_gen_words):
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        pad_encoded = pad_sequences([encoded_text], maxlen = seq_len, truncating='pre') # if tis is more than 25 words truncate the first words (pre words)
        pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0] # brings the index of most probably word
        pred_word = tokenizer.index_word[pred_word_ind]
        
        input_text = ' '+pred_word
        output_text.append(pred_word)
    
    return ' '.join(output_text)
    

In [104]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [105]:
import random 
random.seed(101)
random_pick = random.randint(0, len(text_sequences))

In [106]:
random_seed_text = text_sequences[random_pick]

In [107]:
seed_text = " ".join(random_seed_text)

In [108]:
seed_text

'and throwing the clothes to one side he really did this in not only a civil but a really kind and charitable way i stood looking'

In [109]:
generate_text(model, tokenizer, seq_len, seed_text=seed_text, num_gen_words=25)

'the the the the the the the the the the the the the the the the the the the the the the the the the'

In [110]:
from keras.models import load_model
model = load_model('epochBIG.h5')

In [113]:
tokenizer = load(open('epochBIG', 'rb'))

In [114]:
generate_text(model, tokenizer, seq_len, seed_text=seed_text, num_gen_words=25)

'at compliance and spinning death iron than dropping under their religion never likewise scatter whatever whatever whatever whatever whatever whatever whatever whatever whatever whatever whatever'