<a href="https://colab.research.google.com/github/serdarbozoglan/NLP/blob/master/Keras/Text_Classification2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import keras
from keras.datasets import reuters

In [0]:
(X_train, y_train), (X_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)
word_index = reuters.get_word_index()

if set a number to num_words it will bring the **most common **that much word. In this case (**None**) it brings all the words in the dataset

In [91]:
X_train[0]

[1,
 27595,
 28842,
 8,
 43,
 10,
 447,
 5,
 25,
 207,
 270,
 5,
 3095,
 111,
 16,
 369,
 186,
 90,
 67,
 7,
 89,
 5,
 19,
 102,
 6,
 19,
 124,
 15,
 90,
 67,
 84,
 22,
 482,
 26,
 7,
 48,
 4,
 49,
 8,
 864,
 39,
 209,
 154,
 6,
 151,
 6,
 83,
 11,
 15,
 22,
 155,
 11,
 15,
 7,
 48,
 9,
 4579,
 1005,
 504,
 6,
 258,
 6,
 272,
 11,
 15,
 22,
 134,
 44,
 11,
 15,
 16,
 8,
 197,
 1245,
 90,
 67,
 52,
 29,
 209,
 30,
 32,
 132,
 6,
 109,
 15,
 17,
 12]

In [92]:
y_train[0]

3

In [93]:
type(y_train)

numpy.ndarray

In [94]:
set(y_train)

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45}

We have** 46 different labels **for the news

In [95]:
print(f"# of Training Sentences {len(X_train)}")
print(f"# of Test Sentences     {len(X_test)}")
num_classes = max(y_train) +1 # due to class name 0, we add 1
print(f"# of classess             {num_classes}")

# of Training Sentences 8982
# of Test Sentences     2246
# of classess             46


In [96]:
print(X_train[0]) # the sequence of most frequent words.
print(y_train[0]) # label number is 3

[1, 27595, 28842, 8, 43, 10, 447, 5, 25, 207, 270, 5, 3095, 111, 16, 369, 186, 90, 67, 7, 89, 5, 19, 102, 6, 19, 124, 15, 90, 67, 84, 22, 482, 26, 7, 48, 4, 49, 8, 864, 39, 209, 154, 6, 151, 6, 83, 11, 15, 22, 155, 11, 15, 7, 48, 9, 4579, 1005, 504, 6, 258, 6, 272, 11, 15, 22, 134, 44, 11, 15, 16, 8, 197, 1245, 90, 67, 52, 29, 209, 30, 32, 132, 6, 109, 15, 17, 12]
3


In [97]:
word_index['money']
# 'money' is tge 236th most frequent word in our corpus

236

In [0]:
# let's check from index to word

index_to_word = {}

# we will flip the dictionary
for key, value in word_index.items():
  index_to_word[value] = key

In [99]:
index_to_word[236]

'money'

In [100]:
print(" ".join([index_to_word[x] for x in X_train[0]]))

the wattie nondiscriminatory mln loss for plc said at only ended said commonwealth could 1 traders now april 0 a after said from 1985 and from foreign 000 april 0 prices its account year a but in this mln home an states earlier and rise and revs vs 000 its 16 vs 000 a but 3 psbr oils several and shareholders and dividend vs 000 its all 4 vs 000 1 mln agreed largely april 0 are 2 states will billion total and against 000 pct dlrs


In [0]:
from keras.preprocessing.text import Tokenizer
max_words=10000 # we want only most frequent 10000 words

tokenizer = Tokenizer(num_words = max_words)

X_train = tokenizer.sequences_to_matrix(X_train, mode='binary') 
# binary is used for if the word in first 10000 it will get 1, otherwise 0

X_test = tokenizer.sequences_to_matrix(X_test, mode='binary') 

In [0]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [109]:
print(f"X_train shape: {X_train.shape}")
print(X_train[0])

#print(f"X_test shape : {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(y_train[0]) # 46 lable is one-hot encoded, 3rd label is shown as 1
#print(f"y_test shape : {y_test.shape}")

X_train shape: (8982, 10000)
[0. 1. 0. ... 0. 0. 0.]
y_train shape: (8982, 46)
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [110]:

sum(X_train[0]) 
# there are 56 words from 10000 word-vector in the first document

56.0

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

In [114]:
model =Sequential()

model.add(Dense(512, input_shape=(max_words, )))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(num_classes))
model.add(Activation('softmax'))

W0319 17:06:10.789990 140420596017024 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [116]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.metrics_names)

['loss', 'acc']


In [120]:
batch_size = 32
epochs = 2
history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_split=0.1)
score = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=1)
print(f"Test loss     :{score[0]}")
print(f"Test accuracy :{score[1]}")

Train on 8083 samples, validate on 899 samples
Epoch 1/2
8083/8083 [==============================] - 25s 3ms/step - loss: 0.1805 - acc: 0.9547 - val_loss: 1.0780 - val_acc: 0.8053
Epoch 2/2
2246/2246 [==============================] - 1s 519us/step
Test loss     :1.048913890935434
Test accuracy :0.8000890472215515


In [122]:
print(X_train[0])
print(max(X_train[0]))

[0. 1. 0. ... 0. 0. 0.]
1.0


In [0]:
## This part will be a kinda repitation. We will compare tokenixation method
## And will compare the performance

#  TOKENIZATION FOR BINARY REPRESENTATION OF WORDS (EITHER IN 10000 WORDS NOT NOT)

X_train = tokenizer.sequences_to_matrix(X_train, mode='binary') 
# binary is used for if the word in first 10000 it will get 1, otherwise 0

X_test = tokenizer.sequences_to_matrix(X_test, mode='binary')

y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

model = Sequential()
model.add(Dense(512, input_shape=(max_words, )))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(num_classes))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [126]:
batch_size = 32
epochs = 2

history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)
score = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=1)

print(f"Test accuracy {score[1]}")

Train on 8083 samples, validate on 899 samples
Epoch 1/2
8083/8083 [==============================] - 25s 3ms/step - loss: 0.9446 - acc: 0.7955 - val_loss: 0.8450 - val_acc: 0.8209
Epoch 2/2
2246/2246 [==============================] - 1s 564us/step
Test accuracy 0.808993766696349


In [0]:
## TOKENIZATION FOR COUNT REPRESENTATION OF WORDS 

In [127]:
(X_train, y_train), (X_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)
X_train = tokenizer.sequences_to_matrix(X_train, mode='count') 
X_test = tokenizer.sequences_to_matrix(X_test, mode='count')

y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

print(X_train[0])
print(max(X_train[0]))

[0. 1. 0. ... 0. 0. 0.]
6.0


This time we convert mode from Binary to Count. This ** counts all 1s** in the vector. Means brings the number of words which are already in 10000 words.

In [0]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words, )))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(num_classes))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [129]:
batch_size = 32
epochs = 2

history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)
score = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=1)

print(f"Test accuracy {score[1]}")

Train on 8083 samples, validate on 899 samples
Epoch 1/2
8083/8083 [==============================] - 25s 3ms/step - loss: 1.3358 - acc: 0.7221 - val_loss: 0.9628 - val_acc: 0.8053
Epoch 2/2
2246/2246 [==============================] - 1s 514us/step
Test accuracy 0.8121104185218165


In [0]:
## TOKENIZATION FOR FREQUENCY REPRESENTATION OF WORDS 

In [130]:
(X_train, y_train), (X_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)
X_train = tokenizer.sequences_to_matrix(X_train, mode='freq') 
X_test = tokenizer.sequences_to_matrix(X_test, mode='freq')

y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

print(X_train[0])
print(max(X_train[0]))

[0.         0.01149425 0.         ... 0.         0.         0.        ]
0.06896551724137931


This is very similar to Count but it is **scaled**

In [0]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words, )))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(num_classes))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [132]:
batch_size = 32
epochs = 2

history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)
score = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=1)

print(f"Test accuracy {score[1]}")

Train on 8083 samples, validate on 899 samples
Epoch 1/2
8083/8083 [==============================] - 24s 3ms/step - loss: 2.3287 - acc: 0.4398 - val_loss: 1.9128 - val_acc: 0.5006
Epoch 2/2
2246/2246 [==============================] - 1s 504us/step
Test accuracy 0.5890471950398952


In [0]:
## TOKENIZATION FOR TFIDF REPRESENTATION OF WORDS 

In [134]:
(X_train, y_train), (X_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)

tokenizer.fit_on_sequences(X_train)

X_train = tokenizer.sequences_to_matrix(X_train, mode='tfidf') 
X_test = tokenizer.sequences_to_matrix(X_test, mode='tfidf')

y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

print(X_train[0])
print(max(X_train[0]))

[0.         0.69309152 0.         ... 0.         0.         0.        ]
6.214608098422191


In [0]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words, )))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(num_classes))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [136]:
batch_size = 32
epochs = 2

history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)
score = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=1)

print(f"Test accuracy {score[1]}")

Train on 8083 samples, validate on 899 samples
Epoch 1/2
8083/8083 [==============================] - 30s 4ms/step - loss: 1.2552 - acc: 0.7553 - val_loss: 0.9498 - val_acc: 0.8276
Epoch 2/2
2246/2246 [==============================] - 1s 508us/step
Test accuracy 0.8045414069456812


In [140]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [143]:
from nltk.corpus import wordnet

# Initializing the list of synnonyms and antonyms
synonyms = []
antonyms = []

for syn in wordnet.synsets("good"):
    for s in syn.lemmas():
        synonyms.append(s.name())
        for a in s.antonyms():
            antonyms.append(a.name())
            
            
# Displaying the synonyms and antonyms
print(set(synonyms))
print(set(antonyms))


{'skillful', 'practiced', 'soundly', 'unspoilt', 'goodness', 'dear', 'full', 'thoroughly', 'respectable', 'just', 'skilful', 'beneficial', 'good', 'dependable', 'proficient', 'secure', 'trade_good', 'honest', 'ripe', 'expert', 'well', 'effective', 'serious', 'in_force', 'commodity', 'undecomposed', 'sound', 'salutary', 'upright', 'near', 'safe', 'honorable', 'adept', 'unspoiled', 'right', 'in_effect', 'estimable'}
{'bad', 'evilness', 'ill', 'badness', 'evil'}
